title: Jiefang Xiao's Homepage
page-top-title: Jiefang Xiao
top-section-bg-text: Mathematics & Machine Learning
home-subtitle: Jiefang Xiao&ensp;|&ensp;萧杰方
copyright-text: '&copy; Jiefang Xiao 2024-2026. All Rights Reserved.'
